[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:uvicorn]
command=/opt/venv/bin/uvicorn app.main:app --host 0.0.0.0 --port %(ENV_PORT)s
directory=/app
environment=PYTHONPATH="/app"
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:celery]
command=/opt/venv/bin/celery -A app.worker.celery_app.celery_app worker --loglevel=info -Q default,high_priority,long_running --concurrency=2
directory=/app
environment=PYTHONPATH="/app"
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
