"""add_fk_user_session

Revision ID: a43ad48e9a1b
Revises: c1f70ee49300
Create Date: 2026-03-30 22:06:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a43ad48e9a1b'
down_revision: Union[str, None] = 'c1f70ee49300'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        'fk_sessions_user_id_users', 
        'sessions', 
        'users', 
        ['user_id'], 
        ['id'], 
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_sessions_user_id_users', 'sessions', type_='foreignkey')
    # ### end Alembic commands ###
